/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsul.lpoo_sistemaestacionamentoifsul.view;

import com.mycompany.lpoo_sistemaestacionamentoifsul.dao.PersistenciaJPA;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.stream.Collectors;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Veiculo;

/**
 *
 * @author paula
 */
public class TelaVeiculo extends javax.swing.JFrame {
    PersistenciaJPA jpa;

    /**
     * Creates new form TelaVeiculo
     */
    public TelaVeiculo() {
        initComponents();
        jpa = new PersistenciaJPA();
        
        carregarVeiculosCadastrados();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup3 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        lblPlaca = new javax.swing.JLabel();
        txtBuscaPlaca = new javax.swing.JTextField();
        lblOficial = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        checkOficial = new javax.swing.JCheckBox();
        checkNaoOficial = new javax.swing.JCheckBox();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setText("Veículos cadastrados");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Placa", "Proprietário", "Oficial"
            }
        ));
        tblTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblTable);

        lblPlaca.setText("Placa:");

        txtBuscaPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaPlacaActionPerformed(evt);
            }
        });

        lblOficial.setText("Oficial:");

        checkOficial.setText("Oficial");
        checkOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOficialActionPerformed(evt);
            }
        });

        checkNaoOficial.setText("Não Oficial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkOficial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkNaoOficial)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOficial)
                    .addComponent(checkNaoOficial))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo))
                .addGap(41, 41, 41)
                .addComponent(lblOficial)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnNovo)
                        .addGap(72, 72, 72)
                        .addComponent(btnEditar)
                        .addGap(76, 76, 76)
                        .addComponent(btnRemover)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlaca)
                            .addComponent(txtBuscaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblOficial))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        TelaCadastroVeiculo telaCadastroVei
                = new TelaCadastroVeiculo(this, rootPaneCheckingEnabled);
        telaCadastroVei.setVisible(true);

        carregarVeiculosCadastrados();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int row = tblTable.getSelectedRow();
        if (row >= 0) {
            Veiculo veiSel = (Veiculo) tblTable.getValueAt(row, 0);
            System.out.println("Veículo: " + veiSel.getId());
            try {
                jpa.conexaoAberta();
                int delOp = JOptionPane.showConfirmDialog(this,
                        "Tem certeza que deseja remover " + veiSel.getPlaca() + "?");
                if (delOp == JOptionPane.YES_OPTION) {
                    jpa.remover(veiSel);
                }
                jpa.fecharConexao();
                carregarVeiculosCadastrados();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Erro ao remover pessoa " + veiSel + "\n" + e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um veículo para remover");
        }
       
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void tblTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblTableKeyReleased
        String textoPlaca = txtBuscaPlaca.getText(); // txtBuscaPlaca é o campo de texto para buscar pela placa
    List<Veiculo> veiculosFiltrados;

    try {
        jpa.conexaoAberta();
        veiculosFiltrados = jpa.getVeiculos(textoPlaca); // Método que retorna veículos filtrados pela placa
        jpa.fecharConexao();

        carregarVeiculosCadastrados(veiculosFiltrados); // Chamada do método sobrecarregado
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao filtrar veículos: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_tblTableKeyReleased

    private void checkOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOficialActionPerformed
        boolean somenteOficiais = checkOficial.isSelected(); // checkOficial é a checkbox
    List<Veiculo> veiculosFiltrados;

    try {
        jpa.conexaoAberta();
        veiculosFiltrados = jpa.getVeiculosOficiais(somenteOficiais); // Método que retorna veículos filtrados por oficialidade
        jpa.fecharConexao();

        carregarVeiculosCadastrados(veiculosFiltrados); // Chamada do método sobrecarregado
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao filtrar veículos oficiais: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_checkOficialActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
 int row = tblTable.getSelectedRow();
        if (row >= 0) {
            Veiculo veiSel = (Veiculo) tblTable.getValueAt(row, 0);
            TelaCadastroVeiculo telaEdt = new TelaCadastroVeiculo(this, rootPaneCheckingEnabled);
            telaEdt.setVeiculo(veiSel);
            telaEdt.setVisible(true);
            
            
            carregarVeiculosCadastrados();
            
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um veículo para Editar");
    }          }//GEN-LAST:event_btnEditarActionPerformed

    private void txtBuscaPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPessoa().setVisible(true);
            }
        });
    }
    
    public void carregarVeiculosCadastrados() {
    try {
        jpa.conexaoAberta();
        List<Veiculo> veiculos = jpa.getVeiculos();
        DefaultTableModel model = (DefaultTableModel) tblTable.getModel();
        model.setRowCount(0); // Limpa a tabela

        for (Veiculo v : veiculos) {
            model.addRow(new Object[]{v.getPlaca(), v.getProprietario().getNome()});
        }
        jpa.fecharConexao();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar veículos: " + e.getMessage());
    }
}
    
    public void carregarVeiculosCadastrados(List<Veiculo> veiculosFiltrados) {
    // Limpa a tabela antes de carregar os novos dados
    DefaultTableModel model = (DefaultTableModel) tblTable.getModel();
    model.setRowCount(0); // Limpa todas as linhas

    // Verifica se a lista não está vazia
    if (veiculosFiltrados != null && !veiculosFiltrados.isEmpty()) {
        // Adiciona os veículos na tabela
        for (Veiculo veiculo : veiculosFiltrados) {
            model.addRow(new Object[]{
                veiculo.getPlaca(),
                veiculo.getModelo(),
                veiculo.getCor()
    
            });
        }
    } else {
        JOptionPane.showMessageDialog(this, "Nenhum veículo encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }
}
    
    /*private void atualizarTabela(List<Veiculo> veiculos) {
    DefaultTableModel model = (DefaultTableModel) tblTable.getModel(); 
    model.setRowCount(0); // Limpa a tabela antes de adicionar os novos dados

    for (Veiculo v : veiculos) {
        model.addRow(new Object[]{v.getPlaca(), v.getProprietario().getNome()});
    }*/

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox checkNaoOficial;
    private javax.swing.JCheckBox checkOficial;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOficial;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextField txtBuscaPlaca;
    // End of variables declaration//GEN-END:variables
}
